spring:
  config:
    activate:
      on-profile: prod
  redis:
    host: study-redis
    port: 6379
  session:
    timeout: 600
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://study-database:3306/CStudy
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GoogleId}
            client-secret: ${GoogleSecret}
            scope:
              - email
              - profile


jwt:
  secretKey: ${JwtSecretKey}
  refreshKey: ${JwtRefreshKey}

cloud:
  aws:
    credentials:
      accessKey: ${accessAws}
      secretKey: ${secretAws}
    s3:
      bucket: j4j-test-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

  #logging:
  #  slack:
  #    webhook-uri: ${webhook}
  #  config: classpath:log4j2.xml