spring:
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6379
  session:
    timeout: 600
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CStudy?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 20
      maxLifetime: 295000
      poolName: HikariCP
      readOnly: false
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mail:
    host: smtp.naver.com
    port: 465
    username: ${email_user}
    password: ${email_password}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${clientId}
            client-secret: ${clientSecret}
            scope:
              - email
              - profile

server:
  tomcat:
    threads:
      max: 18
      min-spare: 18
    accept-count: 300
  port: 8080

jwt:
  secretKey: ${secretKey}
  refreshKey: ${refreshKey}

cloud:
  aws:
    credentials:
      accessKey: ${s3AccessKey}
      secretKey: ${s3SecretKey}
    s3:
      bucket: ${bucket}
    region:
      static: ${region}
    stack:
      auto: false

  #logging:
  #  slack:
  #    webhook-uri: ${webhook}
  #  config: classpath:log4j2.xml