spring:
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6379
  session:
    timeout: 600
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CStudy
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${clientId}
            client-secret: ${clientSecret}
            scope:
              - email
              - profile


jwt:
  secretKey: ${secretKey}
  refreshKey: ${refreshKey}

cloud:
  aws:
    credentials:
      accessKey: ${s3AccessKey}
      secretKey: ${s3SecretKey}
    s3:
      bucket: j4j-test-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

  #logging:
  #  slack:
  #    webhook-uri: ${webhook}
  #  config: classpath:log4j2.xml