spring:
  config:
    activate:
      on-profile: prod
  redis:
    host: ${redis_host}
    port: 6379
  session:
    timeout: 600
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql_url}
    username: ${db_name}
    password: ${db_password}
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 20
      maxLifetime: 295000
      poolName: HikariCP
      readOnly: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mail:
    host: smtp.naver.com
    port: 465
    username: ${email}
    password: ${email_password}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${client_id}
            client-secret: ${client_secret}
            scope:
              - email
              - profile

server:
  tomcat:
    threads:
      max: 18
      min-spare: 18
    accept-count: 300
  port: 8080

jwt:
  secretKey: ${secret_key}
  refreshKey: ${refresh_key}

cloud:
  aws:
    credentials:
      accessKey: ${access_key}
      secretKey: ${secret_key}
    s3:
      bucket: ${bucket}
    region:
      static: ${region}
    stack:
      auto: false

logging:
  slack:
    webhook-uri: ${webhook}
  config: classpath:log4j2.xml