spring:
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6379
  session:
    timeout: 600
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/CStudy?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 20
      maxLifetime: 295000
      poolName: HikariCP
      readOnly: false
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mail:
    host: smtp.naver.com
    port: 465
    username: pos04167@naver.com
    password: ngeon4167!
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1031965508463-lfmqeg8qjg7el0sqovh3c02slbv58p22.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

server:
  tomcat:
    threads:
      max: 18
      min-spare: 18
    accept-count: 300
  port: 8080

jwt:
  secretKey: "0123456789012345678901234567890123456789"
  refreshKey: "0123456789012345678901234567890123456789"

cloud:
  aws:
    credentials:
      accessKey: "AKIATRTDCFACRZWYL7EW"
      secretKey: "8WQisx/Rl0DkIHGoshjW254t2coFFFBmfMTTDIPzqppbhnm"
    s3:
      bucket: j4j-test-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

